name: Run CI

on: [push,pull_request]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Test and Publish
      run: |
        chmod a+x build.sh
        ./build.sh
