name: Run CI

on: [pushX,pull_requestX]

jobs:

  build:
 
    runs-on: ubuntu-16.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Test and Publish
      run: |
        chmod a+x build_in_container.sh
        ./build_in_container.sh
